name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  timer_builder: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - image/
    - svg/
